format: HDF5
sourceFile: /home/mwolters138/Downloads/NEONDSImagingSpectrometerData.h5 #h5ex_t_arrayatt.h5
datasets:
  - all
embedding: word2vec
writer: filewriter
astra:
  database: test
  keyspace: test
  table: test
  scb: /home/username/scb
file: /home/username/data
