format: HDF5
sourceFile: <<insert location of source hdf5 file>>
datasets:
  - all
embedding: word2vec
writer: filewriter
astra:
  scb: <<insert location of Astra scb>>
  clientId: <<Astra client ID>>
  clientSecret: <<Astra client secret>>
  keyspace: <<Name of Astra keyspace>>
  query: INSERT INTO vectors25(key, value) VALUES (?,?)
targetFile: <<insert location of target file>>

