format: HDF5
sourceFile: /home/mwolters138/Downloads/embeddings.h5
datasets:
  - name: dataset1
    type: string
  - name: dataset2
    type: int
embedding: word2vec
writer: filewriter
astra:
  database: test
  keyspace: test
  table: test
  scb: /home/username/scb
file: /home/username/data
