format: HDF5
sourceFile: /home/mwolters138/Downloads/NEONDSTowerTemperatureData.hdf5
datasets:
  - all
embedding: word2vec
writer: filewriter
astra:
  database: test
  keyspace: test
  table: test
  scb: /home/username/scb
file: /home/username/data
